/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carousel: typeof import('vue3-carousel')['Carousel']
    ColorSelector: typeof import('./src/components/ColorSelector.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    MainNavigation: typeof import('./src/components/MainNavigation.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Pagination: typeof import('vue3-carousel')['Pagination']
    QuantitySelector: typeof import('./src/components/QuantitySelector.vue')['default']
    Rating: typeof import('./src/components/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCart: typeof import('./src/components/ShoppingCart.vue')['default']
    SizeSelector: typeof import('./src/components/SizeSelector.vue')['default']
    Slide: typeof import('vue3-carousel')['Slide']
    StockInfo: typeof import('./src/components/StockInfo.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
